#!/usr/bin/python

SERVER_ADDRESS = "192.168.1.106"

IMAGE_RESOLUTION = (640, 480)

IMAGE_BYTE_SIZE = IMAGE_RESOLUTION[0] * IMAGE_RESOLUTION[1] * 3

GRAYSCALE_IMAGE_BYTE_SIZE = IMAGE_RESOLUTION[0] * IMAGE_RESOLUTION[1]

DISCOVER_GRAY_SERVICE   = 3068
DISCOVER_COLOR_SERVICE  = 3069
COLOR_SERVICE           = 3070
GRAYSCALE_SERVICE       = 3071

SERVICE_DISCOVER_REQUEST_HEADER = "WHERE_IS_"