#ifndef HEADER_PI_VIS_CONSTANTS
#define HEADER_PI_VIS_CONSTANTS

#include <netinet/in.h>

#define IMAGE_X_SIZE     (640)
#define IMAGE_Y_SIZE     (480)

#define CAMERA_BUF_HEADER_SIZE (8u) /* 4 byte data size, 2 byte xSize, 2 byte ySize */

#define COLOR_IMAGE_SIZE     ((IMAGE_X_SIZE) * (IMAGE_Y_SIZE) * 3)
#define GRAYSCALE_IMAGE_SIZE ((IMAGE_X_SIZE) * (IMAGE_Y_SIZE))

#define IP_ADDRESS_LENGTH INET_ADDRSTRLEN

#define INVALID_32_BIT_INT 0xFFFFFFFF

#define COLOR_PORT_NO (3070)
#define GRAY_PORT_NO (3380)
#define DISCOVER_COLOR_SERVICE (3070)
#define DISCOVER_COLOR_SERVICE_MESSAGE "WHERE_IS_3070"
#define DISCOVER_GRAY_SERVICE (3380)
#define DISCOVER_GRAY_SERVICE_MESSAGE "WHERE_IS_3380"

#define MULTICAST_GROUP "224.1.1.1"

#endif
