#ifndef HEADER_PIVISION_SERVICES
#define HEADER_PIVISION_SERVICES

const uint32_t PIVISION_CAMERA_SERVICE      = 3370u;
const uint32_t PIVISION_COLOR_IMAGE_SERVICE = 3380u;
const uint32_t PIVISION_BW_IMAGE_SERVICE    = 3385u;

#endif
