#ifndef HEADER_PIVISION_SERVICES
#define HEADER_PIVISION_SERVICES

const uint32_t PIVISION_CAMERA_SERVICE_RX      = 3370u;
const uint32_t PIVISION_CAMERA_SERVICE_TX      = PIVISION_CAMERA_SERVICE_RX + 1u;
const uint32_t PIVISION_COLOR_IMAGE_SERVICE_RX = 3380u;
const uint32_t PIVISION_COLOR_IMAGE_SERVICE_TX = PIVISION_COLOR_IMAGE_SERVICE_RX + 1u;
const uint32_t PIVISION_BW_IMAGE_SERVICE_RX    = 3390u;
const uint32_t PIVISION_BW_IMAGE_SERVICE_TX    = PIVISION_BW_IMAGE_SERVICE_RX + 1u;

#endif
