#!/usr/bin/python

IMAGE_RESOLUTION = (640, 480)

IMAGE_BYTE_SIZE = IMAGE_RESOLUTION[0] * IMAGE_RESOLUTION[1] * 3

GRAYSCALE_IMAGE_BYTE_SIZE = IMAGE_RESOLUTION[0] * IMAGE_RESOLUTION[1]

IMAGE_DATA_SERVICE            = 3380

DISCOVER_CAMERA_SERVICE       = 3069
CAMERA_SERVICE                = 3070

SERVICE_DISCOVER_REQUEST_HEADER = "WHERE_IS_"

GRAY_SCALE_IMAGE_TYPE = 0
COLOR_IMAGE_TYPE      = 1
